# Generated by Django 4.2.7 on 2023-11-24 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compañia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('ubicacion', models.CharField(max_length=50, verbose_name='Ubicación')),
            ],
        ),
        migrations.CreateModel(
            name='Personaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('anime', models.CharField(max_length=50, verbose_name='Anime/Serie')),
            ],
        ),
        migrations.CreateModel(
            name='Figura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denominacion', models.CharField(max_length=50, verbose_name='Denominación/Nombre')),
                ('coleccion', models.CharField(max_length=40, verbose_name='Colección/serie')),
                ('precio', models.FloatField(verbose_name='Precio')),
                ('compañias', models.ManyToManyField(to='core.compañia')),
                ('personaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.personaje')),
            ],
        ),
    ]
